# Generated by Django 3.2.25 on 2025-06-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('year_of_pub', models.IntegerField()),
                ('Total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
                ('shelf_location', models.CharField(max_length=100)),
            ],
        ),
    ]
